import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    {
      name: 'generated-cjs-eslint-header',
      generateBundle(_options, bundle) {
        for (const output of Object.values(bundle)) {
          if (output.type === 'chunk' && output.fileName.endsWith('.cjs')) {
            output.code = '/* eslint-disable @typescript-eslint/no-require-imports -- CommonJS requires are generated by Rollup. */\n' + output.code
          }
        }
      },
    },
  ],
  build: {
    lib: {
      entry: {
        index: 'src/index.ts',
        icons: 'src/icons.ts',
        'icons-12-filled': 'src/assets/Icon/12/Filled.tsx',
        'icons-16-stroked': 'src/assets/Icon/16/Stroked.tsx',
        'icons-16-filled': 'src/assets/Icon/16/Filled.tsx',
        'icons-20-filled': 'src/assets/Icon/20/Filled.tsx',
        'icons-20-stroked': 'src/assets/Icon/20/Stroked.tsx',
        'icons-20-stroked-1px': 'src/assets/Icon/20/Stroked1px.tsx',
        'icons-20-graphic': 'src/assets/Icon/20/Graphic.tsx',
        'icons-24-stroked': 'src/assets/Icon/24/Stroked.tsx',
        'icons-24-filled': 'src/assets/Icon/24/Filled.tsx',
        'icons-32-stroked': 'src/assets/Icon/32/Stroked.tsx',
        'icons-32-filled': 'src/assets/Icon/32/Filled.tsx',
      },
      name: 'TDS',
      formats: ['es', 'cjs'],
      fileName: (format, entryName) => {
        const ext = format === 'cjs' ? 'cjs' : 'es.js';
        const nameMap: Record<string, string> = {
          index: format === 'cjs' ? 't-ds.cjs' : 't-ds.es.js',
          icons: format === 'cjs' ? 'icons.cjs' : 'icons.es.js',
          'icons-12-filled': `icons/12/Filled.${ext}`,
          'icons-16-stroked': `icons/16/Stroked.${ext}`,
          'icons-16-filled': `icons/16/Filled.${ext}`,
          'icons-20-filled': `icons/20/Filled.${ext}`,
          'icons-20-stroked': `icons/20/Stroked.${ext}`,
          'icons-20-stroked-1px': `icons/20/Stroked1px.${ext}`,
          'icons-20-graphic': `icons/20/Graphic.${ext}`,
          'icons-24-stroked': `icons/24/Stroked.${ext}`,
          'icons-24-filled': `icons/24/Filled.${ext}`,
          'icons-32-stroked': `icons/32/Stroked.${ext}`,
          'icons-32-filled': `icons/32/Filled.${ext}`,
        };
        return nameMap[entryName] ?? `${entryName}.${ext}`;
      }
    },
    emptyOutDir: true,
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        'react/jsx-runtime',
        'react/jsx-dev-runtime',
      ],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM'
        }
      }
    }
  }
})
